export const FETCH_USER = "FETCH_USER";
export const FETCH_USERDATA = "FETCH_USERDATA";
export const CREATE_USER = "CREATE_USER";
export const FETCH_USER_REQUEST_START = "FETCH_USER_REQUEST_START";
export const FETCH_USER_REQUEST_STOP = "FETCH_USER_REQUEST_STOP";
export const DELETE_USER = "DELETE_USER";
